### ISSUE TITLE
Zero-value kerns are automatically deleted because … ?

### ISSUE THREAD

**Issue by mbutterick** [robofab-developers/robofab#31]
If you write a zero-value kern to an RKerning object, [the kern pair will be deleted](https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/objects/objectsBase.py#L3121).

I find this behavior very surprising. 

First, AFAIK, zero is not a forbidden kern value in any font-data specification ([for instance](http://unifiedfontobject.org/versions/ufo3/kerning.html)). Therefore, it’s odd that Robofab would prevent its use.

Second, zero-value kerns are useful in a variety of situations. 

* For instance, suppose I have an alternate glyph G' that is in a kerning class with G. The two share all their kerns, but there's one glyph X that collides with G' but not G. In that case, I might want to make a zero-value kern for (G', X) to override the bad kern. FontLab will let me add this kern. But if I try to add it programmatically to an RKerning object in Robofab, it will disappear.

* Another example, more closely resembling my use case: suppose you have three fonts, F1 and F2 and F3, that share kerning in an algorithmic way. For instance, F2’s kerning is the same as F1, but +10 on every kern, and F3’s kerning is +10 of F2. What happens to a -10 kern in F1? It becomes 0 in F2 *and gets deleted*. Then F3, which should end up with a +10 kern, ends up with no kern at all on that pair.

Third, this auto-delete behavior goes beyond what is promised in the docs, which is that [“RKerning is a dictionary of kerning values.”](http://robofab.org/objects/kerning.html) Dictionaries don’t spontaneously delete their keys based on the value. 

Perhaps this behavior is too old and entrenched to be changed. But I think the wiser method would be to permit zero-value kerns, and either a) pick a non-numerical value to signal “delete this pair” (for instance, `False`) or b) create a separate function in the RKerning object like `deleteZeroValueKerns` that performs this housekeeping for those who want it.

**Comment by typesupply** [comment]
This dates back to 10+ years ago, but I think I remember the basics of why it works this way. There were two factors: 1. we were just in the beginning of the OpenType days, so a lot of the work was still geared towards Type 1 fonts and zero values in flat kerning were unnecessary; 2. FontLab, the environment that RoboFab was initially written to wrap, did some really nasty things when zero values were present (the source code may even have notes about this). So, they were quietly deleted.

RoboFab is the only library that I have worked on that does this. defcon, fontMath, ufoLib, etc. all support zero values. We've wanted to change the RoboFab behavior for years, leaving the zero value deletion in objectsFL if necessary, but it hasn't ever been a high enough priority to move ahead of other things on our list.

A patch would be welcome!

**Comment by mbutterick** [comment]
After 10 years, it’s probably unpatchable. It’s likely that scripts in the wild have learned to rely on this behavior, so making it right would really be making it wrong. 

As I say, perhaps consider adding a warning to the RKerning docs at robofab.org (I don’t believe those are part of this repo?).
