### ISSUE TITLE
Glyph names converted to case  sensitive file names

### ISSUE THREAD

**Issue by paarandika** [robofab-developers/robofab#43]
I have used this script to generate interpolated instances of .ufo files. But it seemed that those generated ufo objects contains case sensitive file names for glyphs and due to that AFDKO compiled .otf fonts had some glypsh replaced by other. 
When I go in to the robofab code I could find out that `getGlyphNameToFileNameFunc()` in objectsBase.py is returning none since `elf.lib.get("org.robofab.glyphNameToFileNameFuncName")` is null.
Is it because that I don't have the above package in my system?

I could correct the issue by modifying the line
 `glyphNameToFileNameFunc = self.getGlyphNameToFileNameFunc()` 
in objectsRF.py in to something like
   `from robofab.tools.glyphNameSchemes import glyphNameToShortFileName`
`glyphNameToFileNameFunc = glyphNameToShortFileName`
@pathumego

**Comment by benkiel** [comment]
ufoLib should handle this now, see https://github.com/unified-font-object/ufoLib
