### ISSUE TITLE
[ufo3k] RFont.layers is assumed to exist always

### ISSUE THREAD

**Issue by lianghai** [robofab-developers/robofab#44]
``` Python
>>> import robofab.world
>>> f = robofab.world.OpenFont('robofab-ufo3k/Data/DemoFont.ufo')
>>> g = f['A']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lianghai/bin/FDK/Tools/osx/Python/Current/lib/python2.7/site-packages/robofab-ufo3k/Lib/robofab/objects/objectsBase.py", line 184, in __getitem__
    return self.layers.getDefaultLayer()[glyphName]
AttributeError: 'RFont' object has no attribute 'layers'
```

Uh, I started to try using the `ufo3k` branch (the installation in FDK 2.5.64655) to avoid the (lack of) case-sensitivity issue, but somehow it can't handle the absence of layers well (even for the DemoFont.ufo, which, I suppose, must be well-formed in terms of what the `ufo3k` branch expects).

Is it only me? Mmm, am I suppose to explicitly initiate `layers` or apply some other workaround?

**Comment by typesupply** [comment]
The robofab objects in the ufo3k branch are not finished.
