### ISSUE TITLE
[ufo3k] Finish RoboFab Objects in ufo3k branch

### ISSUE THREAD

**Issue by davelab6** [robofab-developers/robofab#46]
https://github.com/robofab-developers/robofab/issues/44 was closed, but I'd like to better understand what objects are pending completion in the ufo3k branch, such that we could whittle away at them.

**Comment by typesupply** [comment]
ufoLib in that branch is done. We're planning to break that out on its own at some point. The other parts of RoboFab are the parts that are stuck because it is more complex than fixing a few things. It needs a re-architecture to eliminate the problems of maintaining the 3rd party environment wrappers. I think Erik and I have discussed this on the RoboFab mailing list. It's on our list of things to do.

**Comment by graphicore** [comment]
> We're planning to break that out on its own at some point.

:+1: That's good news.

Did you ever think about putting the more general pens into their own lib. I'm asking because I'm thinking about that for ufoJS.

**Comment by davelab6** [comment]
> I think Erik and I have discussed this on the RoboFab mailing list. 

I couldn't find any threads about this. 

> It's on our list of things to do.

Are you open to describing what needs to be done such that someone else could contribute it?

**Comment by typesupply** [comment]
@graphicore:

> Did you ever think about putting the more general pens into their own lib. I'm asking because I'm thinking about that for ufoJS.

Yes, sort of. The base PointPen is now part of ufoLib. The other pens that subclass that are still part of RoboFab. Are there some that you think should move?

---

@davelab6:

> I couldn't find any threads about this.

You must not have looked very hard. ;) There is one titled "Robofab, UFO3, python3" that I replied to on September 28, 2014.

> Are you open to describing what needs to be done such that someone else could contribute it?

Eh, describing it is the same as doing it. It's not that I'm being lazy, it's just that other things keep jumping in front (UFO normalization, UFO4 research, etc.). I've sought out help in the past and it hasn't ever worked out. I work on this stuff when I have time, but I have been very busy lately. Also, I fund all of this myself so there isn't a corporate backer covering my expenses if I take a month off to write an API or whatever.

**Comment by davelab6** [comment]
> "Robofab, UFO3, python3"

Thank you :) It sounds like the fastest way to get this done is to fund you to do it; do you have a ballpark figure in mind, and a period in the next year or so you could allocate to this assuming you were adequately funded?

**Comment by graphicore** [comment]
> Are there some that you think should move?

Well, I did not make up my mind completely yet. But with ufoJS I think it's far easier for me to move things around and rearrange them. So I'm thinking of a JavaScript library let's call it "penBox" where all the generally useful pens that are defined somewhere would be collected. That includes pens from fontTools,  RoboFab and ufoLib. From RoboFab that would be all pens that don't require a direct RoboFab dependency i.e. a module from `robofab.objects` or so. The rationale is that I think the pen APIs are a great way to work with outlines and thus can be very useful for people even if they don't use ufoLib or RoboFab. I did so already in some occasions.
For the plan of splitting `ufoLib` and `RoboFab` I also think it could be a good idea to make a "penBox"` that contains all pens that are neither dependent on RoboFab nor on ufoLib. Instead RoboFab and ufoLib would import penBox.

**Comment by adrientetar** [comment]
> Also, I fund all of this myself so there isn't a corporate backer covering my expenses if I take a month off to write an API or whatever.

As I have told you before, this could change if you were to give a number. Anyway, I’m not especially interested in robofab personally (I think its APPI are too burdensome and that a thin range of functions on top of defcon can be far more effective and comfortable to work with at the same time).

**Comment by benkiel** [comment]
Instead, FontParts
