### ISSUE TITLE
Unified documentation

### ISSUE THREAD

**Issue by felipesanches** [robofab-developers/robofab#50]
Apparently we have several instances of documentation efforts for Robofab. I am not sure which one is "official" and which is the most complete:
- http://www.robodocs.info/roboFabDocs/source/index.html
- https://github.com/robofab-developers/robofab/pull/12 (Sphinx-based docs)
- https://github.com/robofab-developers/robofab/tree/master/Documentation

Also there's several domain names, which is confusing:
- http://robofab.org (is listed in the github project description, but seems to be currently offline/unreachable)
- http://www.robodocs.info/
- http://robofab.com

It would be good to at least make sure the URL proeminently placed in the project description is working and easily leads to good documentation.

**Comment by benkiel** [comment]
Updated.

**Comment by felipesanches** [comment]
Thanks! That's better indeed.

But there's still the need to get rid of the other pieces of documentation which may still confuse people.

**Comment by felipesanches** [comment]
In other words, your update fixed the "easy to find" but not the "unified" portion of the issue description, so it would be better to reopen the issue.

**Comment by benkiel** [comment]
The documentation is in a bit of a state of flux as things have moved from different servers and the unified part isn't done yet. Agreed and changing the title.

**Comment by LettError** [comment]
Agreed. 
Robofab.org should go to the same place as the .com. My mistake. I will fix it when I get to a computer. 
Thanks,

Erik

**Comment by benkiel** [comment]
We have pulled the sphinx documentation into Robofab.

**Comment by LettError** [comment]
Thanks Ben!

**Comment by gferreira** [comment]
hello Ben,

this merge request was from April 2014 :) it is no longer up-to-date.

the updated RoboFab docs currently lives here, as a separate repository:

https://github.com/roboDocs/roboFabDocs

it includes the old Sphinx API Docs + the old robofab website (ported to Sphinx).

G

**Comment by gferreira** [comment]
I agree things are messy… I suggest to keep this issue open until everything is sorted out.

just a quick overview, so everybody is on the same page:

the original RoboFab doc was *not* written in Sphinx. as time passed, other projects came along, and Sphinx established itself as the norm for new projects.

by 2013, the RoboFab site was beginning to show signs of age, so I've started to port it to Sphinx  (website + tutorials + API docs). the classic RoboFab stylesheet was also preserved as a Sphinx theme. this work was done in a private fork of robofab, and was completed during 2014.

around this time, together with Frederik, the RoboDocs project was born. the idea is to *collect* individual documentation from all separate modules, so it can be made available from a single central place. RoboDocs is essentially an empty Sphinx project, which pulls content from the separate module documentations (using git submodule).

trying to put some order into all of this:

1. I propose that the Sphinx-based docs (currently in [robodocs/robofabdocs](https://github.com/robodocs/robofabdocs)) should be considered the official from now on. it contains lots of small corrections and updates, and it is a lot easier to mantain. (but please don't take my word for it; have a look and judge for yourself)

2. this updated Sphinx-based docs should be moved into the [official robofab repository](https://github.com/robofab-developers/robofab), replacing the current `Docs` and `Documentation` folders.

3. the separate `robodocs/robofabdocs` repository should be deleted.

4. both robofab.org and RoboDocs.info should simply mirror the Sphinx-based docs.

5. any new contributions to the documentation should be submitted directly to the robofab repository.

I hope this all makes sense.

I everyone is ok with this, I can merge the updated docs and submit a pull request.

**Comment by benkiel** [comment]
Gustavo: Agree, save for what Erik may say about point 4. But, yes, please merge the updated docs and submit a pull request — many thanks!

**Comment by gferreira** [comment]
here's an update on the state of things after this week's work:

- the new Sphinx-based documentation has now been merged to master (thanks @benkiel), the old Documentation folder has been removed. (so points 1+2 above are solved)

- the working copy of the docs has been deleted from [roboDocs/roboFabDocs](https://github.com/roboDocs/roboFabDocs). that repository now contains only the RoboFabDocs extension for RoboFont, for use with Mechanic. (this addresses point 3 above)

remaining tasks (point 4):

- RoboDocs will switch from using ReadTheDocs to simple FTP, to make things simpler. @typemytype has already created a dedicated space on his server, now we just need to plug this into the robodocs.info domain.

- awaiting feedback from @LettError about robofab.org.
