### ISSUE TITLE
[ufo3k] Moving ufoLib out of Robofab

### ISSUE THREAD

**Issue by moyogo** [robofab-developers/robofab#51]
There’s been talks about moving ufoLib into a separate repository.
Is that still happening?
How can we help?

**Comment by moyogo** [comment]
@adrientetar @anthrotype @behdad @brawer @graphicore @jamesgk

**Comment by typesupply** [comment]
I've been giving this a lot of thought and I'd like to transfer the ownership of ufoLib to the UFO Specification. It would be good to include as an example implementation [here](https://github.com/unified-font-object/ufo-example-implementations). I don't have time to make the transfer and, frankly, I'm terrible with Git so I don't know how to do it properly. If anyone wants to do this for me, I'd really appreciate it.

**Comment by adrientetar** [comment]
How about making ufoLib a repository which would be like the current ufo3 branch except the robofab module is pulled? 
Create a repository in the ufo org and give me the rights to it and I'll do that.

**Comment by typesupply** [comment]
Do you mean move robofab/ufo3k/ufoLib to /ufo-example-implementations/tree/master/ufoLib? I'd be happy with that!

**Comment by adrientetar** [comment]
Hm, I was thinking of making ufoLib its own repository in the UFO organization. The reason for this is that we depend on ufoLib and would like a standalone package that contains only ufoLib. 
Do you object doing so?

**Comment by typesupply** [comment]
Ah. So it structurally wouldn't make sense to put it in the example implementations? I'm not being disingenuous or anything. I legitimately am confused about how trees need to be structured for Git. Back in the SVN days I could put different libraries in the same repository and those could be pulled independently.

**Comment by adrientetar** [comment]
As far as I know git, it's optimized for one repo = one piece of software. 
"ufo-example-implementations" is a big bucket that can potentially contain many different things. e.g. moving ufoLib into example-implementations you would have commits to the normalizer and the ufoLib mixed together. 
Also making it a separate repo would let us keep the existing path structure and commits, you can essentially just delete the robofab parts and you have your ufoLib repo ready.

**Comment by adrientetar** [comment]
Okay, it's possible to clone a subdirectory in git with a [sparse checkout](http://stackoverflow.com/questions/600079/is-there-any-way-to-clone-a-git-repositorys-sub-directory-only/13738951#13738951) since 2012, but it is a bit tricky. And I still personally think it's better to give each software its own repository for various reasons (separating commits/issues/etc.).

**Comment by typesupply** [comment]
Okay. Do you think I should restructure the existing branch to be specific to the normalizer?

**Comment by adrientetar** [comment]
Yeah I'd probably do that, so the tools would be structured like your own defcon/ufo2fdk/extractor/etc. repos.

**Comment by typesupply** [comment]
Okay. I'll try to do this in the next few days. Thanks!

**Comment by miguelsousa** [comment]
Agree. I suggest renaming the repo `ufo-example-implementations` to `ufo-normalizer` and update its description.

**Comment by adrientetar** [comment]
👍

By the way if you need help with anything git feel free to post here.

**Comment by moyogo** [comment]
@typesupply Great!
Here’s how you can create a ufoLib repository from the robofab one, preserving the relevant commit history:

* clone
  * `git clone --no-hardlinks https://github.com/robofab-developers/robofab ufoLib`
  * `cd ufoLib`
* checkout the ufo3k branch and make it master
  * `git checkout ufo3k; git branch -D master; git branch -m ufo3k master`
* you could track other remote branches with `git branch -t branchname origin/branchname` but here it seems those branches can be dropped since they don’t have a separate ufoLib
* remove the origin remote and other remote branches
  * `git remote rm origin`
* remove Lib/robofab and Scripts from commits
  * `git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch Lib/robofab Scripts" --prune-empty HEAD`
* general clean up 
  * `git reset --hard`
  * `git show-ref refs/original/* --hash | xargs -n 1 git update-ref -d`
  * `git reflog expire --expire=now --all`
  * `git gc --aggressive --prune=now`
* add new remote
  * `git add remote origin https://github.com/unified-font-object/ufoLib.git`
* push to https://github.com/unified-font-object/ufoLib
  * `git push master -u origin master`

I don’t know if you want to remote Lib/ufoLib from the commit history of the robofab repository (the same `git filter-branch` command can do it) or just `git rm` it to preserve its history here.

**Comment by moyogo** [comment]
BTW shouldn’t glyphNameSchemes.py or at least the [Common User Name to File Name Algorithm](http://unifiedfontobject.org/versions/ufo3/conventions.html#usernametofilename) be in ufoLib?

**Comment by typesupply** [comment]
@adrientetar Okay. I set up a new repository called ufo-reader-writer and set you as a collaborator. Please let me know if I did anything wrong.

@moyogo [It is.](https://github.com/robofab-developers/robofab/blob/ufo3k/Lib/ufoLib/filenames.py) :)

**Comment by anthrotype** [comment]
@typesupply great!
just wondering, why not call the repo just `ufoLib`?

**Comment by adrientetar** [comment]
Yeah, +1 to this ufoLib's cool.

I'll do the migration shortly.

**Comment by adrientetar** [comment]
ufoLib and ufoNormalizer would be cool a naming. And ufoLib matches the name of the library and is shorter.

**Comment by moyogo** [comment]
@typesupply ah yes, sorry robofab’s was being used in some test and I spoke too fast.

ufoLib and ufonormalizer would be nice since that’s what one would import or run. Or maybe even ufolib since there is fonttools but one imports fontTools. Anyway, it might just be nitpicking.

**Comment by adrientetar** [comment]
@moyogo are your py23 changes for robofab ready? Maybe we should get that merged before splitting.

**Comment by moyogo** [comment]
@adrientetar #54

**Comment by typesupply** [comment]
I changed the repository names.

**Comment by adrientetar** [comment]
There is exactly one dependency remaining to robofab in the split ufoLib, it's PointToSegmentPen to interface with fontTools.

**Comment by adrientetar** [comment]
Since ufoLib is supposed to own the pointPen, shouldn't it hold the ways to convert to the more Postscript-like segmentPen?

**Comment by typesupply** [comment]
> Since ufoLib is supposed to own the pointPen, shouldn't it hold the ways to convert to the more Postscript-like segmentPen?

Yes. PointToSegmentPen should move to ufoLib.

**Comment by jackjennings** [comment]
Now that roboFab development is shifting to working on [typesupply/fontParts], is it possible to extract the current implementation of ufoLib into its own package?

Currently fontParts depends on defcon, which in turn depends on robofab for ufoLib. This is somewhat logical given the transition and scaffolding, but it seems like to make fontParts successful ufoLib needs to be extracted sooner than later.

**Comment by benkiel** [comment]
Jack, UFOLib was broken out of Robofab a bit ago: https://github.com/unified-font-object/ufoLib

**Comment by jackjennings** [comment]
Sounds like I need to submit a pull request to defcon then. Should this issue be closed?

**Comment by adrientetar** [comment]
Yes.

**Comment by typesupply** [comment]
That would be great. The ufo3 branch is the place to do that.

**Comment by benkiel** [comment]
UFOLib has been moved out of Robofab to https://github.com/unified-font-object/ufoLib

**Comment by miguelsousa** [comment]
@benkiel #68
