### ISSUE TITLE
[ufo3k] Error in save() at objectsRF

### ISSUE THREAD

**Issue by paarandika** [robofab-developers/robofab#53]
I get an error when I try to invoke save() on new font. Code works in "master" branch without any issues and on "ufo3k" it fails. Full stack trace is below.
```python
File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsRF.py", line 471, in save
    glyph = self[glyphName]
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsBase.py", line 184, in __getitem__
    return self.layers.getDefaultLayer()[glyphName]
AttributeError: 'RFont' object has no attribute 'layers'
```

**Comment by typesupply** [comment]
The R* objects in the ufo3k branch is incomplete and is not going to be completed. UFO 3 support is going to be accomplished by a rewrite. The ufo3k branch objects were an experiment that failed.
