### ISSUE TITLE
why BaseContour.draw(pen) always closes path?

### ISSUE THREAD

**Issue by anthrotype** [robofab-developers/robofab#58]
I know robofab/master is in maintenance mode only, but I spotted something which does not make sense to me.

https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/objects/objectsBase.py#L1947-L1950

```python
			if firstType == MOVE and (firstOn.x, firstOn.y) == (lastOn.x, lastOn.y):
				closed = True
			else:
				closed = True
```

A few lines later, this is followed by this:
https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/objects/objectsBase.py#L1947-L1950
```python
			if closed:
				pen.closePath()
			else:
				pen.endPath()
```

because `closed` is always `True`, `endPath` is never executed.

cc @LettError

**Comment by LettError** [comment]
Why is "closed is always true"?

**Comment by adrientetar** [comment]
Clearly the code should be

```
            if firstType == MOVE and (firstOn.x, firstOn.y) == (lastOn.x, lastOn.y):
                closed = True
            elif firstType == MOVE:
                closed = False
            else:
                closed = True
```

**Comment by anthrotype** [comment]
because Fontlab.
